mod contracts;
mod history;
mod settings;
pub use contracts::*;
pub use history::*;
pub use settings::*;
pub mod income_tax;
pub mod projection;
pub mod tax_rules_india;
pub mod tax_year;
pub mod withholding;
pub use projection::{calculate_projection, TaxProjection, TaxProjectionInput};
