use async_graphql::{InputObject, SimpleObject, ID};
use chrono::{DateTime, NaiveDate, Utc};
use super::types::{AppraisalAnswerDto, ReviewCycleDto};

#[derive(InputObject)] pub struct PerformanceProgramPolicyInput { pub performance_program_id: ID, pub population_mode: String, #[graphql(default)] pub population_ids: Vec<ID>, pub goal_setting_due_days: Option<i32>, pub self_review_due_days: Option<i32>, pub manager_review_due_days: Option<i32>, pub calibration_due_days: Option<i32>, pub acknowledgement_due_days: Option<i32> }
#[derive(InputObject)] pub struct PerformanceAdminCyclesInput { pub cursor: Option<String>, #[graphql(default = 20)] pub limit: i32, pub status: Option<String>, pub performance_program_id: Option<ID> }
#[derive(InputObject)] pub struct PerformancePopulationOptionsInput { pub mode: String, pub search: Option<String>, pub cursor: Option<String>, #[graphql(default = 50)] pub limit: i32 }
#[derive(InputObject)] pub struct PrivatePerformanceFeedbackInput { pub participant_id: ID, pub cursor: Option<String>, #[graphql(default = 20)] pub limit: i32 }
#[derive(InputObject)] pub struct SavePerformanceCalibrationInput { pub participant_id: ID, pub expected_revision: i32, pub final_rating: String, pub performance_band: Option<String>, pub reason: String }
#[derive(InputObject)] pub struct ReopenPerformanceReviewInput { pub participant_id: ID, pub expected_revision: i32, pub correction_stage: String, pub reason: String }
#[derive(InputObject)] pub struct SetPerformanceParticipantExcludedInput { pub participant_id: ID, pub excluded: bool, pub reason: String }
#[derive(InputObject)] pub struct AddPrivatePerformanceFeedbackInput { pub participant_id: ID, pub goal_id: Option<ID>, pub observation_date: NaiveDate, pub comments: String }
#[derive(InputObject)] pub struct SavePerformanceKpiTargetInput { pub participant_id: ID, pub goal_id: ID, pub id: Option<ID>, pub metric_name: String, pub target_value: Option<String>, pub unit: Option<String> }
#[derive(InputObject)] pub struct SubmitPerformanceKpiActualInput { pub participant_id: ID, pub goal_kpi_id: ID, pub expected_revision: i32, pub actual_value: Option<String>, pub evidence: Option<String>, pub comment: Option<String>, pub measurement_date: Option<NaiveDate> }

#[derive(SimpleObject, Clone)] pub struct PerformanceProgramPolicyDto { pub performance_program_id: ID, pub archived_at: Option<DateTime<Utc>>, pub population_mode: String, pub population_ids: Vec<ID>, pub goal_setting_due_days: Option<i32>, pub self_review_due_days: Option<i32>, pub manager_review_due_days: Option<i32>, pub calibration_due_days: Option<i32>, pub acknowledgement_due_days: Option<i32> }
#[derive(SimpleObject, Clone)] pub struct PerformanceStageDeadlineDto { pub stage: String, pub due_date: NaiveDate }
#[derive(SimpleObject, Clone)] pub struct PerformanceGoalKpiDto { pub id: ID, pub goal_id: ID, pub metric_name: String, pub target_value: Option<String>, pub actual_value: Option<String>, pub unit: Option<String>, pub evidence: Option<String>, pub comment: Option<String>, pub measurement_date: Option<NaiveDate> }
#[derive(SimpleObject, Clone)] pub struct PerformanceAdminExceptionDto { pub id: ID, pub exception_code: String, pub details: String, pub resolved_at: Option<DateTime<Utc>>, pub created_at: DateTime<Utc> }
#[derive(SimpleObject, Clone)] pub struct PerformancePopulationOptionDto { pub id: ID, pub name: String, pub department_id: Option<ID>, pub location_id: Option<ID> }
#[derive(SimpleObject, Clone)] pub struct PerformancePopulationOptionsDto { pub items: Vec<PerformancePopulationOptionDto>, pub next_cursor: Option<String> }
#[derive(SimpleObject, Clone)] pub struct PerformanceReviewRevisionDto { pub revision: i32, pub reopened_at: Option<DateTime<Utc>>, pub reopened_by_user_id: Option<ID>, pub reopen_reason: Option<String>, pub correction_stage: Option<String>, pub self_submitted_at: Option<DateTime<Utc>>, pub manager_submitted_at: Option<DateTime<Utc>>, pub acknowledged_at: Option<DateTime<Utc>>, pub manager_rating: Option<String>, pub final_rating: Option<String>, pub performance_band: Option<String>, pub calibration_provenance: Option<String> }
#[derive(SimpleObject, Clone)] pub struct PerformanceCalibrationDecisionDto { pub id: ID, pub revision: i32, pub final_rating: String, pub performance_band: Option<String>, pub reason: String, pub decided_by_user_id: ID, pub decided_at: DateTime<Utc> }
#[derive(SimpleObject, Clone)] pub struct PerformanceParticipantAdministrationDto { pub participant_id: ID, pub employee_id: ID, pub employee_name: String, pub manager_employee_id: Option<ID>, pub status: String, pub is_excluded: bool, pub exclusion_reason: Option<String>, pub response_revision: i32, pub self_submitted_at: Option<DateTime<Utc>>, pub manager_submitted_at: Option<DateTime<Utc>>, pub acknowledged_at: Option<DateTime<Utc>>, pub manager_rating: Option<String>, pub final_rating: Option<String>, pub performance_band: Option<String>, pub calibration_provenance: Option<String>, pub revisions: Vec<PerformanceReviewRevisionDto> }
#[derive(SimpleObject, Clone)] pub struct PerformanceFeedbackPageDto { pub items: Vec<super::types::PerformanceFeedbackDto>, pub next_cursor: Option<String> }
#[derive(SimpleObject, Clone)] pub struct PerformanceAdminCycleDto { pub review_cycle: ReviewCycleDto, pub current_stage: String, pub participant_count: i64, pub excluded_participant_count: i64, pub actionable_exception_count: i64 }
#[derive(SimpleObject, Clone)] pub struct PerformanceAdminCyclePageDto { pub items: Vec<PerformanceAdminCycleDto>, pub next_cursor: Option<String> }
#[derive(SimpleObject, Clone)] pub struct PerformanceCycleAdministrationDto { pub review_cycle: ReviewCycleDto, pub current_stage: String, pub deadlines: Vec<PerformanceStageDeadlineDto>, pub participants: Vec<PerformanceParticipantAdministrationDto>, pub next_participant_cursor: Option<String>, pub exceptions: Vec<PerformanceAdminExceptionDto> }
#[derive(SimpleObject, Clone)] pub struct PerformanceReviewRevisionDetailDto { pub review: PerformanceReviewRevisionDto, pub answers: Vec<AppraisalAnswerDto>, pub kpis: Vec<PerformanceGoalKpiDto>, pub calibrations: Vec<PerformanceCalibrationDecisionDto>, pub acknowledgement_comment: Option<String> }
